server:
  port: 8081

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5433/identity_db
    username: flowops
    password: flowops_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true